-- Generated by umber/neovim.py — do not edit by hand.
return {
  normal = {
    a = { fg = "#171614", bg = "#ed8347", gui = "bold" },
    b = { fg = "#b7aaa1", bg = "#392f28" },
    c = { fg = "#83786e", bg = "#281f19" },
  },
  insert = {
    a = { fg = "#171614", bg = "#7a9e6d", gui = "bold" },
    b = { fg = "#b7aaa1", bg = "#392f28" },
    c = { fg = "#83786e", bg = "#281f19" },
  },
  visual = {
    a = { fg = "#171614", bg = "#a37a95", gui = "bold" },
    b = { fg = "#b7aaa1", bg = "#392f28" },
    c = { fg = "#83786e", bg = "#281f19" },
  },
  replace = {
    a = { fg = "#171614", bg = "#c16956", gui = "bold" },
    b = { fg = "#b7aaa1", bg = "#392f28" },
    c = { fg = "#83786e", bg = "#281f19" },
  },
  command = {
    a = { fg = "#171614", bg = "#be863a", gui = "bold" },
    b = { fg = "#b7aaa1", bg = "#392f28" },
    c = { fg = "#83786e", bg = "#281f19" },
  },
  terminal = {
    a = { fg = "#171614", bg = "#72a7a7", gui = "bold" },
    b = { fg = "#b7aaa1", bg = "#392f28" },
    c = { fg = "#83786e", bg = "#281f19" },
  },
  inactive = {
    a = { fg = "#83786e", bg = "#281f19" },
    b = { fg = "#83786e", bg = "#281f19" },
    c = { fg = "#83786e", bg = "#281f19" },
  },
}
