-- Generated by umber/neovim.py — do not edit by hand.
return {
  normal = {
    a = { fg = "#f9f4ee", bg = "#a74900", gui = "bold" },
    b = { fg = "#3f352d", bg = "#ded2c8" },
    c = { fg = "#776c63", bg = "#f1e6dd" },
  },
  insert = {
    a = { fg = "#f9f4ee", bg = "#4f6f2a", gui = "bold" },
    b = { fg = "#3f352d", bg = "#ded2c8" },
    c = { fg = "#776c63", bg = "#f1e6dd" },
  },
  visual = {
    a = { fg = "#f9f4ee", bg = "#775679", gui = "bold" },
    b = { fg = "#3f352d", bg = "#ded2c8" },
    c = { fg = "#776c63", bg = "#f1e6dd" },
  },
  replace = {
    a = { fg = "#f9f4ee", bg = "#a53c27", gui = "bold" },
    b = { fg = "#3f352d", bg = "#ded2c8" },
    c = { fg = "#776c63", bg = "#f1e6dd" },
  },
  command = {
    a = { fg = "#f9f4ee", bg = "#885700", gui = "bold" },
    b = { fg = "#3f352d", bg = "#ded2c8" },
    c = { fg = "#776c63", bg = "#f1e6dd" },
  },
  terminal = {
    a = { fg = "#f9f4ee", bg = "#2d7068", gui = "bold" },
    b = { fg = "#3f352d", bg = "#ded2c8" },
    c = { fg = "#776c63", bg = "#f1e6dd" },
  },
  inactive = {
    a = { fg = "#776c63", bg = "#f1e6dd" },
    b = { fg = "#776c63", bg = "#f1e6dd" },
    c = { fg = "#776c63", bg = "#f1e6dd" },
  },
}
