-- Generated by umber/neovim.py — do not edit by hand.
return {
  normal = {
    a = { fg = "#171614", bg = "#f98e53", gui = "bold" },
    b = { fg = "#ddd0c6", bg = "#392f28" },
    c = { fg = "#a0948a", bg = "#271f19" },
  },
  insert = {
    a = { fg = "#171614", bg = "#a0ca92", gui = "bold" },
    b = { fg = "#ddd0c6", bg = "#392f28" },
    c = { fg = "#a0948a", bg = "#271f19" },
  },
  visual = {
    a = { fg = "#171614", bg = "#cc9cbb", gui = "bold" },
    b = { fg = "#ddd0c6", bg = "#392f28" },
    c = { fg = "#a0948a", bg = "#271f19" },
  },
  replace = {
    a = { fg = "#171614", bg = "#f7907a", gui = "bold" },
    b = { fg = "#ddd0c6", bg = "#392f28" },
    c = { fg = "#a0948a", bg = "#271f19" },
  },
  command = {
    a = { fg = "#171614", bg = "#eead56", gui = "bold" },
    b = { fg = "#ddd0c6", bg = "#392f28" },
    c = { fg = "#a0948a", bg = "#271f19" },
  },
  terminal = {
    a = { fg = "#171614", bg = "#96d3d3", gui = "bold" },
    b = { fg = "#ddd0c6", bg = "#392f28" },
    c = { fg = "#a0948a", bg = "#271f19" },
  },
  inactive = {
    a = { fg = "#a0948a", bg = "#271f19" },
    b = { fg = "#a0948a", bg = "#271f19" },
    c = { fg = "#a0948a", bg = "#271f19" },
  },
}
