-- Generated by umber/neovim.py — do not edit by hand.
return {
  normal = {
    a = { fg = "#f8f7f5", bg = "#a74900", gui = "bold" },
    b = { fg = "#40372e", bg = "#e0d5ca" },
    c = { fg = "#786e64", bg = "#f2e9df" },
  },
  insert = {
    a = { fg = "#f8f7f5", bg = "#506e2c", gui = "bold" },
    b = { fg = "#40372e", bg = "#e0d5ca" },
    c = { fg = "#786e64", bg = "#f2e9df" },
  },
  visual = {
    a = { fg = "#f8f7f5", bg = "#775679", gui = "bold" },
    b = { fg = "#40372e", bg = "#e0d5ca" },
    c = { fg = "#786e64", bg = "#f2e9df" },
  },
  replace = {
    a = { fg = "#f8f7f5", bg = "#a33e2b", gui = "bold" },
    b = { fg = "#40372e", bg = "#e0d5ca" },
    c = { fg = "#786e64", bg = "#f2e9df" },
  },
  command = {
    a = { fg = "#f8f7f5", bg = "#885700", gui = "bold" },
    b = { fg = "#40372e", bg = "#e0d5ca" },
    c = { fg = "#786e64", bg = "#f2e9df" },
  },
  terminal = {
    a = { fg = "#f8f7f5", bg = "#2d706c", gui = "bold" },
    b = { fg = "#40372e", bg = "#e0d5ca" },
    c = { fg = "#786e64", bg = "#f2e9df" },
  },
  inactive = {
    a = { fg = "#786e64", bg = "#f2e9df" },
    b = { fg = "#786e64", bg = "#f2e9df" },
    c = { fg = "#786e64", bg = "#f2e9df" },
  },
}
