-- Generated by umber/neovim.py — do not edit by hand.
return {
  normal = {
    a = { fg = "#161a21", bg = "#f98e53", gui = "bold" },
    b = { fg = "#cdd8e3", bg = "#2e363f" },
    c = { fg = "#909aa5", bg = "#1e262d" },
  },
  insert = {
    a = { fg = "#161a21", bg = "#a5c586", gui = "bold" },
    b = { fg = "#cdd8e3", bg = "#2e363f" },
    c = { fg = "#909aa5", bg = "#1e262d" },
  },
  visual = {
    a = { fg = "#161a21", bg = "#d1aad3", gui = "bold" },
    b = { fg = "#cdd8e3", bg = "#2e363f" },
    c = { fg = "#909aa5", bg = "#1e262d" },
  },
  replace = {
    a = { fg = "#161a21", bg = "#ff9a84", gui = "bold" },
    b = { fg = "#cdd8e3", bg = "#2e363f" },
    c = { fg = "#909aa5", bg = "#1e262d" },
  },
  command = {
    a = { fg = "#161a21", bg = "#ebab54", gui = "bold" },
    b = { fg = "#cdd8e3", bg = "#2e363f" },
    c = { fg = "#909aa5", bg = "#1e262d" },
  },
  terminal = {
    a = { fg = "#161a21", bg = "#84c8c3", gui = "bold" },
    b = { fg = "#cdd8e3", bg = "#2e363f" },
    c = { fg = "#909aa5", bg = "#1e262d" },
  },
  inactive = {
    a = { fg = "#909aa5", bg = "#1e262d" },
    b = { fg = "#909aa5", bg = "#1e262d" },
    c = { fg = "#909aa5", bg = "#1e262d" },
  },
}
