-- Generated by umber/neovim.py — do not edit by hand.
return {
  normal = {
    a = { fg = "#f8f7f5", bg = "#a74900", gui = "bold" },
    b = { fg = "#40372e", bg = "#e0d5ca" },
    c = { fg = "#786e64", bg = "#f2e9df" },
  },
  insert = {
    a = { fg = "#f8f7f5", bg = "#446d36", gui = "bold" },
    b = { fg = "#40372e", bg = "#e0d5ca" },
    c = { fg = "#786e64", bg = "#f2e9df" },
  },
  visual = {
    a = { fg = "#f8f7f5", bg = "#8b5d7c", gui = "bold" },
    b = { fg = "#40372e", bg = "#e0d5ca" },
    c = { fg = "#786e64", bg = "#f2e9df" },
  },
  replace = {
    a = { fg = "#f8f7f5", bg = "#ab4834", gui = "bold" },
    b = { fg = "#40372e", bg = "#e0d5ca" },
    c = { fg = "#786e64", bg = "#f2e9df" },
  },
  command = {
    a = { fg = "#f8f7f5", bg = "#865600", gui = "bold" },
    b = { fg = "#40372e", bg = "#e0d5ca" },
    c = { fg = "#786e64", bg = "#f2e9df" },
  },
  terminal = {
    a = { fg = "#f8f7f5", bg = "#206363", gui = "bold" },
    b = { fg = "#40372e", bg = "#e0d5ca" },
    c = { fg = "#786e64", bg = "#f2e9df" },
  },
  inactive = {
    a = { fg = "#786e64", bg = "#f2e9df" },
    b = { fg = "#786e64", bg = "#f2e9df" },
    c = { fg = "#786e64", bg = "#f2e9df" },
  },
}
